const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(require('path').resolve(__dirname,'../index.html'),'utf8');
function fn(name){const start=html.indexOf('async function '+name+'(')>=0?html.indexOf('async function '+name+'('):html.indexOf('function '+name+'(');return html.slice(start,html.indexOf('\n}',start)+2);}
let passed=0;
function setup({pay='cod',failAuth=false,failWrite=false,qty=2}={}){
 const calls=[], saved=new Map();let uploaded=null;
 const product={id:'tea',name:'Tea',price:100000,images:['images/tea.jpg'],stock:100,sales:0};
 const elements={cName:{value:'Customer'},cPhone:{value:'02012345678'},cAddr:{value:'Vientiane'},cEmail:{value:''},cCity:{value:''},cCountry:{value:'LA'},cNote:{value:''},paymentSlip:{files:pay==='bank-vn'?[{name:'slip.png',type:'image/png',size:12}]:[]}};
 const context={console:{log(){},error(){}},crypto:{randomUUID:()=> 'receipt-id'},document:{getElementById:id=>elements[id],querySelector:q=>({value:q.includes('ship')?'vn':pay})},getCart:()=>[{id:'tea',qty}],getProduct:()=>product,getProducts:()=>[product],Store:{get:(k,d)=>saved.has(k)?saved.get(k):d,set:(k,v)=>saved.set(k,v),remove:k=>saved.delete(k)},setCart:v=>calls.push(['cart',v]),setOrderStatus:(...v)=>calls.push(['status',...v]),setOrderBtn(){},t:k=>k,isFirebaseConfigured:()=>({ok:true}),safeStorageName:s=>s,isProofPaymentMethod:p=>['bank-vn','bcel','qr'].includes(p),setTimeout(){},navigate(){},window:{LCFB:{db:{},collection:(db,n)=>n,serverTimestamp:()=> 'SERVER_TIME',lcEnsureOrderUser:async()=>{calls.push(['auth']);if(failAuth)throw {code:'auth/operation-not-allowed',message:'Disabled'};return {uid:'alice'}},storage:{},storageRef:(st,p)=>p,uploadBytes:async(p,f)=>{calls.push(['upload',p]);uploaded=p;return {ref:p}},getDownloadURL:async()=> 'https://firebasestorage.googleapis.com/v0/b/lotus-1a491.firebasestorage.app/o/test',addDoc:async(col,data)=>{calls.push(['write',col,data]);if(failWrite)throw {code:'permission-denied',message:'Denied'};return {id:'order-id'}}}}};
 vm.createContext(context);vm.runInContext(fn('placeOrder'),context);
 return {context,calls,saved};
}
async function test(name,run){await run();console.log('PASS '+(++passed)+' '+name)}
(async()=>{
 await test('COD authenticates, sets UID and sends compact item path',async()=>{const x=setup();await x.context.placeOrder();const w=x.calls.find(c=>c[0]==='write');assert.equal(w[2].ownerUid,'alice');assert.equal(w[2].items[0].image,'images/tea.jpg');assert.equal(w[2].total,230000);assert.equal(w[2].createdAt,'SERVER_TIME');assert.equal(x.calls[0][0],'status');assert.ok(x.calls.findIndex(c=>c[0]==='auth')<x.calls.findIndex(c=>c[0]==='write'));assert.ok(x.saved.has('lastOrder'));assert.equal(x.context.placeOrder.busy,false)});
 await test('bank receipt uploaded under authenticated UID before write',async()=>{const x=setup({pay:'bank-vn'});await x.context.placeOrder();const w=x.calls.find(c=>c[0]==='write')[2];assert.equal(w.slipPath,'payment-slips/alice/receipt-id-slip.png');assert.equal(w.paymentStatus,'pending');assert.equal(w.slipSize,12);assert.ok(x.calls.findIndex(c=>c[0]==='upload')<x.calls.findIndex(c=>c[0]==='write'))});
 await test('auth failure preserves cart, no order write',async()=>{const x=setup({failAuth:true});await x.context.placeOrder();assert.equal(x.calls.some(c=>c[0]==='write'||c[0]==='cart'),false);assert.equal(x.context.placeOrder.busy,false)});
 await test('permission failure preserves cart and has project diagnostic',async()=>{const x=setup({failWrite:true});await x.context.placeOrder();assert.equal(x.calls.some(c=>c[0]==='cart'),false);assert.ok(x.calls.some(c=>c[0]==='status'&&String(c[1]).includes('lotus-1a491')))});
 await test('invalid item blocked before network',async()=>{const x=setup({qty:-1});await x.context.placeOrder();assert.equal(x.calls.some(c=>c[0]==='auth'||c[0]==='write'),false)});
 await test('double submit causes one write',async()=>{const x=setup();await Promise.all([x.context.placeOrder(),x.context.placeOrder()]);assert.equal(x.calls.filter(c=>c[0]==='write').length,1)});
 await test('customer listener uses UID filter',()=>{let filters,listener;const c={window:{LCFB:{ready:true,auth:{currentUser:{uid:'alice'}},db:{},collection:(db,n)=>n,where:(...args)=>args,query:(...args)=>{filters=args;return args},onSnapshot:(q,callback)=>{listener=callback;return ()=>{}}},addEventListener(){}},isFirebaseAdmin:()=>false,parseHash:()=>({page:'home'}),router(){}};vm.createContext(c);vm.runInContext(fn('resetOrderSubscription')+'\n'+fn('subscribeOrdersIfNeeded'),c);c.subscribeOrdersIfNeeded();assert.equal(filters[1][0],'ownerUid');assert.equal(filters[1][2],'alice');c.resetOrderSubscription();assert.equal(c.window._fbOrders.length,0)});
 await test('admin flag in localStorage cannot grant role',()=>{const c={window:{LCFB:{auth:{currentUser:{uid:'alice'}}},LCSession:{uid:'bob',isAdmin:true}},Store:{get:()=>true}};vm.createContext(c);vm.runInContext(fn('isFirebaseAdmin'),c);assert.equal(c.isFirebaseAdmin(),false)});
 console.log('ALL '+passed+' CHECKOUT TESTS PASSED');
})().catch(e=>{console.error(e);process.exitCode=1});
