const fs=require('fs');
const {initializeTestEnvironment,assertSucceeds,assertFails}=require('@firebase/rules-unit-testing');
const {doc,setDoc,getDoc,getDocs,collection,query,where,updateDoc,deleteDoc,serverTimestamp}=require('firebase/firestore');
const {ref,uploadBytes,getMetadata}=require('firebase/storage');
const path=require('path').resolve(__dirname,'..')+'/';
let count=0, env;
async function test(name, f){await f(); console.log('PASS '+(++count)+' '+name);}
function order(uid,extra={}){return {ownerUid:uid,name:'Customer',phone:'02012345678',address:'Vientiane',customer:{name:'Customer',phone:'02012345678',addr:'Vientiane',email:'',city:'',country:'LA',note:''},items:[{id:'product-1',name:'Tea',price:100000,qty:2,image:'images/tea.jpg'}],subtotal:200000,shipFee:30000,discount:0,total:230000,shipMethod:'vn',payMethod:'cod',coupon:null,status:'pending',paymentStatus:'pending',slipUrl:'',slipPath:'',slipName:'',slipType:'',slipSize:0,slipUploadedAt:null,createdAt:serverTimestamp(),...extra};}
(async()=>{
 env=await initializeTestEnvironment({projectId:'demo-lotus-orders',firestore:{host:'127.0.0.1',port:8181,rules:fs.readFileSync(path+'firestore.rules','utf8')},storage:{host:'127.0.0.1',port:9299,rules:fs.readFileSync(path+'storage.rules','utf8')}});
 await env.clearFirestore();
 const a=env.authenticatedContext('alice',{email:'alice@example.com'}),b=env.authenticatedContext('bob',{email:'bob@example.com'}),guest=env.authenticatedContext('guest',{firebase:{sign_in_provider:'anonymous'}}),admin=env.authenticatedContext('admin',{email:'admin@example.com'}),none=env.unauthenticatedContext();
 await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'admins/admin'),{enabled:true});await setDoc(doc(c.firestore(),'orders/legacy'),{name:'Old',status:'pending',paymentStatus:'pending'});});
 const adb=a.firestore(),bdb=b.firestore(),mdb=admin.firestore();
 await test('signed-out create denied',()=>assertFails(setDoc(doc(none.firestore(),'orders/noauth'),order('alice'))));
 await test('owner creates COD order',()=>assertSucceeds(setDoc(doc(adb,'orders/a'),order('alice'))));
 await test('anonymous authenticated checkout',()=>assertSucceeds(setDoc(doc(guest.firestore(),'orders/g'),order('guest'))));
 await test('forged owner denied',()=>assertFails(setDoc(doc(adb,'orders/forged'),order('bob'))));
 for(const [name,change] of Object.entries({missingPhone:{phone:''},paid:{paymentStatus:'paid'},badTotal:{total:1},badSubtotal:{subtotal:0,total:30000},extraRole:{admin:true},emptyItems:{items:[]},negativeQty:{items:[{id:'x',name:'X',price:100,qty:-1,image:''}]},badImage:{items:[{id:'x',name:'X',price:100,qty:1,image:'data:image/png;base64,x'}]},clientTimestamp:{createdAt:new Date(0)},oversizeName:{name:'x'.repeat(151)}})){
  await test('invalid '+name+' denied',()=>assertFails(setDoc(doc(adb,'orders/bad-'+name),order('alice',change))));
 }
 const twenty=Array.from({length:20},(_,i)=>({id:'p'+i,name:'Product',price:100,qty:1,image:''}));
 await test('20 items safely rejected above limit',()=>assertFails(setDoc(doc(adb,'orders/twenty'),order('alice',{items:twenty,subtotal:2000,total:32000}))));
 const five=twenty.slice(0,5); await test('5 items within evaluation limit',()=>assertSucceeds(setDoc(doc(adb,'orders/five'),order('alice',{items:five,subtotal:500,total:30500}))));
 const lastBad=five.map(x=>({...x}));lastBad[4].qty=0;
 await test('last item validated',()=>assertFails(setDoc(doc(adb,'orders/last-bad'),order('alice',{items:lastBad,subtotal:400,total:30400}))));
 const middleBad=five.map(x=>({...x}));middleBad[2].qty=-1;
 await test('middle item negative quantity denied',()=>assertFails(setDoc(doc(adb,'orders/middle-bad'),order('alice',{items:middleBad,subtotal:300,total:30300}))));
 await test('forged subtotal with consistent total denied',()=>assertFails(setDoc(doc(adb,'orders/forged-sum'),order('alice',{subtotal:100,total:30100}))));
 const extraItem=five.map(x=>({...x}));extraItem[2].role='admin';
 await test('middle item extra fields denied',()=>assertFails(setDoc(doc(adb,'orders/middle-extra'),order('alice',{items:extraItem,subtotal:500,total:30500}))));
 const slip={payMethod:'bank-vn',slipUrl:'https://firebasestorage.googleapis.com/v0/b/lotus-1a491.firebasestorage.app/o/payment-slips%2Falice%2Fx.png?alt=media&token=test',slipPath:'payment-slips/alice/x.png',slipName:'x.png',slipType:'image/png',slipSize:12,slipUploadedAt:new Date().toISOString()};
 await test('5 item bank order accepted',()=>assertSucceeds(setDoc(doc(adb,'orders/bank5'),order('alice',{...slip,items:five,subtotal:500,total:30500}))));
 await test('bank order accepted pending review',()=>assertSucceeds(setDoc(doc(adb,'orders/bank'),order('alice',slip))));
 await test('foreign slip path denied',()=>assertFails(setDoc(doc(adb,'orders/foreign-slip'),order('alice',{...slip,slipPath:'payment-slips/bob/x.png'}))));
 await test('owner reads own',()=>assertSucceeds(getDoc(doc(adb,'orders/a'))));
 await test('other customer cannot read',()=>assertFails(getDoc(doc(bdb,'orders/a'))));
 await test('public read denied',()=>assertFails(getDoc(doc(none.firestore(),'orders/a'))));
 await test('owner query accepted',()=>assertSucceeds(getDocs(query(collection(adb,'orders'),where('ownerUid','==','alice')))));
 await test('customer unfiltered query denied',()=>assertFails(getDocs(collection(adb,'orders'))));
 await test('admin query accepted',()=>assertSucceeds(getDocs(collection(mdb,'orders'))));
 await test('customer cannot change status',()=>assertFails(updateDoc(doc(adb,'orders/a'),{status:'completed'})));
 await test('admin changes status',()=>assertSucceeds(updateDoc(doc(mdb,'orders/a'),{status:'confirmed'})));
 await test('admin marks paid with timestamp',()=>assertSucceeds(updateDoc(doc(mdb,'orders/bank'),{paymentStatus:'paid',paymentReviewedAt:serverTimestamp()})));
 await test('admin cannot rewrite owner',()=>assertFails(updateDoc(doc(mdb,'orders/a'),{ownerUid:'bob'})));
 await test('customer delete denied',()=>assertFails(deleteDoc(doc(adb,'orders/a'))));
 await test('admin deletes order',()=>assertSucceeds(deleteDoc(doc(mdb,'orders/twenty'))));
 await test('legacy order visible to admin',()=>assertSucceeds(getDoc(doc(mdb,'orders/legacy'))));
 await test('legacy order hidden from customer',()=>assertFails(getDoc(doc(adb,'orders/legacy'))));
 await test('legacy status update by admin',()=>assertSucceeds(updateDoc(doc(mdb,'orders/legacy'),{status:'confirmed'})));
 const profile={uid:'alice',name:'Alice',email:'alice@example.com',phone:'',createdAt:serverTimestamp()};
 await test('own profile creation',()=>assertSucceeds(setDoc(doc(adb,'users/alice'),profile)));
 await test('own profile read',()=>assertSucceeds(getDoc(doc(adb,'users/alice'))));
 await test('own profile update',()=>assertSucceeds(updateDoc(doc(adb,'users/alice'),{name:'Alice 2'})));
 await test('foreign profile blocked',()=>assertFails(getDoc(doc(bdb,'users/alice'))));
 await test('profile role escalation denied',()=>assertFails(updateDoc(doc(adb,'users/alice'),{admin:true})));
 await test('admin role self creation denied',()=>assertFails(setDoc(doc(adb,'admins/alice'),{enabled:true})));
 await test('missing own role readable',()=>assertSucceeds(getDoc(doc(adb,'admins/alice'))));
 await test('foreign role blocked',()=>assertFails(getDoc(doc(adb,'admins/admin'))));
 const image=new Uint8Array([137,80,78,71]);
 await test('owner uploads receipt',()=>assertSucceeds(uploadBytes(ref(a.storage(),'payment-slips/alice/a.png'),image,{contentType:'image/png'})));
 await test('foreign receipt upload denied',()=>assertFails(uploadBytes(ref(b.storage(),'payment-slips/alice/b.png'),image,{contentType:'image/png'})));
 await test('html receipt denied',()=>assertFails(uploadBytes(ref(a.storage(),'payment-slips/alice/a.html'),image,{contentType:'text/html'})));
 await test('owner reads receipt',()=>assertSucceeds(getMetadata(ref(a.storage(),'payment-slips/alice/a.png'))));
 await test('foreign receipt read denied',()=>assertFails(getMetadata(ref(b.storage(),'payment-slips/alice/a.png'))));
 await test('admin reads receipt',()=>assertSucceeds(getMetadata(ref(admin.storage(),'payment-slips/alice/a.png'))));
 await test('public receipt read denied',()=>assertFails(getMetadata(ref(none.storage(),'payment-slips/alice/a.png'))));
 await test('fixed admin UID reads orders',()=>assertSucceeds(getDocs(collection(env.authenticatedContext('fmkw0LyA8yWYYZBbePmDx3g5JWE2').firestore(),'orders'))));
 console.log('ALL '+count+' SECURITY TESTS PASSED');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(env)await env.cleanup();});
